/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValueAddedServicesRouteImport } from './routes/value-added-services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ClienteleRouteImport } from './routes/clientele'
import { Route as IndexRouteImport } from './routes/index'

const ValueAddedServicesRoute = ValueAddedServicesRouteImport.update({
  id: '/value-added-services',
  path: '/value-added-services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteleRoute = ClienteleRouteImport.update({
  id: '/clientele',
  path: '/clientele',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientele': typeof ClienteleRoute
  '/products': typeof ProductsRoute
  '/solutions': typeof SolutionsRoute
  '/value-added-services': typeof ValueAddedServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientele': typeof ClienteleRoute
  '/products': typeof ProductsRoute
  '/solutions': typeof SolutionsRoute
  '/value-added-services': typeof ValueAddedServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientele': typeof ClienteleRoute
  '/products': typeof ProductsRoute
  '/solutions': typeof SolutionsRoute
  '/value-added-services': typeof ValueAddedServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/clientele' | '/products' | '/solutions' | '/value-added-services'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clientele' | '/products' | '/solutions' | '/value-added-services'
  id:
    | '__root__'
    | '/'
    | '/clientele'
    | '/products'
    | '/solutions'
    | '/value-added-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteleRoute: typeof ClienteleRoute
  ProductsRoute: typeof ProductsRoute
  SolutionsRoute: typeof SolutionsRoute
  ValueAddedServicesRoute: typeof ValueAddedServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/value-added-services': {
      id: '/value-added-services'
      path: '/value-added-services'
      fullPath: '/value-added-services'
      preLoaderRoute: typeof ValueAddedServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientele': {
      id: '/clientele'
      path: '/clientele'
      fullPath: '/clientele'
      preLoaderRoute: typeof ClienteleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteleRoute: ClienteleRoute,
  ProductsRoute: ProductsRoute,
  SolutionsRoute: SolutionsRoute,
  ValueAddedServicesRoute: ValueAddedServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
